In [1]:
from Bio.PDB import PDBParser, PDBIO
from Bio.PDB.Structure import Structure as BStructure
from Bio.PDB.Model import Model as BModel
from Bio.PDB.Chain import Chain as BChain
from Bio.PDB.Residue import Residue as BResidue
from Bio.PDB.Atom import Atom as BAtom

In [2]:
import json
import pickle
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from multiprocessing import Pool
from tqdm import tqdm

from utils import *

Random seed set as 42


In [3]:
seqs = json.load(open("./data/sequence_pairs.json", "rb"))
len(seqs)

5403

In [11]:
# get xyz of each AA
for i in tqdm(range(len(seqs))):
    
#     if seqs[i]["pdb"]!="7pgb":
#         continue
    
    # Heavy chain
    seqs[i]["Hpos"] = get_residue_pos("../SAbDab_20221124/all_structures/raw/{}.pdb".format(seqs[i]["pdb"]), chain=seqs[i]["Hchain"])

    # Light chain
    seqs[i]["Lpos"] = get_residue_pos("../SAbDab_20221124/all_structures/raw/{}.pdb".format(seqs[i]["pdb"]), chain=seqs[i]["Lchain"])

    # Antigen chains
    seqs[i]["Apos"] = []
#     Achains = seqs[i]["Achain"].split(" | ")
#     for j in range(len(Achains)):
#         seqs[i]["Apos"].append(get_residue_pos("../SAbDab_20221124/all_structures/raw/{}.pdb".format(seqs[i]["pdb"]), chain=Achains[j]))

    for j in range(len(seqs[i]["Achain"])):
        seqs[i]["Apos"].append(get_residue_pos("../SAbDab_20221124/all_structures/raw/{}.pdb".format(seqs[i]["pdb"]), chain=seqs[i]["Achain"][j]))
        
    
#     break

100%|████████████████████████████████████████████████████████████████████████████| 5403/5403 [1:13:35<00:00,  1.22it/s]


In [12]:
seqs[i]["Hchain"]

'H'

In [13]:
seqs[i]

{'pdb': '3vi3',
 'Hchain': 'H',
 'Lchain': 'L',
 'Achain': ['D'],
 'Hseq': ['QVHLQQSGAELMKPGASVKISCKATGYTFTSYWIEWVKQRPGHGLEWLGEILPGSGYIHYNEKFKGKATFTTDTSSNTAYMQLSSLTSEDSAVYYCSRALALYAMDYWGQGTSVTVSSAKTTPPSVYPLAPGSAAQTNSMVTLGCLVKGYFPEPVTVTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVPSSTWPSETVTCNVAHPASSTKVDKKIVPR'],
 'Lseq': ['DIVMTQATPSIPVTPGESVSISCRSNKSLLHSNGNTYLYWFLQRPGQSPRLLIFRMSNLASGVPDRFSGSGSGTAFTLRISRVEAADVGIYFCLQHLEYPFTFGAGTKLELKRADAAPTVSIFPPSSEQLTSGGASVVCFLNNFYPKDINVKWKIDGSERQNGVLNSWTDQDSKDSTYSMSSTLTLTKDEYERHNSYTCEATHKTSTSPIVKSFNRNEC'],
 'Aseq': ['QTDENRCLKANAKSCGECIQAGPNCGWCTNSTFLQEGMPTSARCDDLEALKKKGCPPDDIENPRGSKDIKKNKNVTNRSKGTAEKLKPEDIHQIQPQQLVLRLRSGEPQTFTLKFKRAEDYPIDLYYLMDLSYSMKDDLENVKSLGTDLMNEMRRITSDFRIGFGSFVEKTVMPYISTTPAKLRNPCTSEQNCTTPFSYKNVLSLTNKGEVFNELVGKQRISGNLDSPEGGFDAIMQVAVCGSLIGWRNVTRLLVFSTDAGFHFAGDGKLGGIVLPNDGQCHLENNMYTMSHYYDYPSIAHLVQKLSENNIQTIFAVTEEFQPVYKELKNLIPKSAVGTLSANSSNVIQLIIDAYNSLSSEVILENGKLSEGVTISYKSYCKNGVNGTGENGRKCSNISIGDEVQFEISITSNKCPKKDSDSFKIRPLGFTEEVEVILQYICECEGGLENLYFQ']

In [15]:
seqs[i]

{'pdb': '3vi3',
 'Hchain': 'H',
 'Lchain': 'L',
 'Achain': ['D'],
 'Hseq': ['QVHLQQSGAELMKPGASVKISCKATGYTFTSYWIEWVKQRPGHGLEWLGEILPGSGYIHYNEKFKGKATFTTDTSSNTAYMQLSSLTSEDSAVYYCSRALALYAMDYWGQGTSVTVSSAKTTPPSVYPLAPGSAAQTNSMVTLGCLVKGYFPEPVTVTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVPSSTWPSETVTCNVAHPASSTKVDKKIVPR'],
 'Lseq': ['DIVMTQATPSIPVTPGESVSISCRSNKSLLHSNGNTYLYWFLQRPGQSPRLLIFRMSNLASGVPDRFSGSGSGTAFTLRISRVEAADVGIYFCLQHLEYPFTFGAGTKLELKRADAAPTVSIFPPSSEQLTSGGASVVCFLNNFYPKDINVKWKIDGSERQNGVLNSWTDQDSKDSTYSMSSTLTLTKDEYERHNSYTCEATHKTSTSPIVKSFNRNEC'],
 'Aseq': ['QTDENRCLKANAKSCGECIQAGPNCGWCTNSTFLQEGMPTSARCDDLEALKKKGCPPDDIENPRGSKDIKKNKNVTNRSKGTAEKLKPEDIHQIQPQQLVLRLRSGEPQTFTLKFKRAEDYPIDLYYLMDLSYSMKDDLENVKSLGTDLMNEMRRITSDFRIGFGSFVEKTVMPYISTTPAKLRNPCTSEQNCTTPFSYKNVLSLTNKGEVFNELVGKQRISGNLDSPEGGFDAIMQVAVCGSLIGWRNVTRLLVFSTDAGFHFAGDGKLGGIVLPNDGQCHLENNMYTMSHYYDYPSIAHLVQKLSENNIQTIFAVTEEFQPVYKELKNLIPKSAVGTLSANSSNVIQLIIDAYNSLSSEVILENGKLSEGVTISYKSYCKNGVNGTGENGRKCSNISIGDEVQFEISITSNKCPKKDSDSFKIRPLGFTEEVEVILQYICECEGGLENLYFQ']

In [16]:
"../SAbDab_20221124/all_structures/raw/{}.pdb".format(seqs[i]["pdb"]), seqs[i]["Hchain"]

('../SAbDab_20221124/all_structures/raw/3vi3.pdb', 'H')

In [17]:
i = 777

pdb_path = "../SAbDab_20221124/all_structures/raw/{}.pdb".format(seqs[i]["pdb"])

chain=seqs[i]["Hchain"]
# chain=seqs[i]["Lchain"]
# chain=Achains[j]

In [18]:
get_residue_pos("../SAbDab_20221124/all_structures/raw/{}.pdb".format(seqs[i]["pdb"]), chain=seqs[i]["Hchain"])

[array([[-95.963,   7.249, -59.086],
        [-95.747,   7.294, -60.528],
        [-95.821,   8.724, -61.056],
        [-95.13 ,   9.078, -62.011]], dtype=float32),
 array([[-96.661,   9.544, -60.426],
        [-96.81 ,  10.95 , -60.796],
        [-95.581,  11.68 , -60.263],
        [-95.509,  12.017, -59.079]], dtype=float32),
 array([[-94.604,  11.923, -61.135],
        [-93.297,  12.392, -60.703],
        [-92.775,  13.476, -61.634],
        [-93.249,  13.657, -62.762]], dtype=float32),
 array([[-91.775,  14.194, -61.125],
        [-91.075,  15.255, -61.843],
        [-89.587,  14.932, -61.748],
        [-88.961,  15.173, -60.711]], dtype=float32),
 array([[-89.024,  14.372, -62.814],
        [-87.611,  14.014, -62.844],
        [-86.847,  15.214, -63.389],
        [-87.021,  15.594, -64.548]], dtype=float32),
 array([[-86.01 ,  15.825, -62.559],
        [-85.265,  17.001, -62.976],
        [-83.774,  16.697, -63.043],
        [-83.261,  15.832, -62.327]], dtype=float32),
 array([[-

In [19]:
p = PDBParser()

structure = p.get_structure('input', pdb_path)

AA_coord = []
chain = chain.lower() if chain not in [c.get_id() for c in structure[0].get_list()] else chain
print(chain, pdb_path)
for residue in structure[0][chain]:
    if residue.get_resname() not in AA_abbr:
        continue

    for temp_atom in residue:
        break

    try:
        N_coord = residue['N'].get_coord()
    except:
        N_coord = temp_atom.get_coord()
    try:
        CA_coord = residue['CA'].get_coord()
    except:
        CA_coord = temp_atom.get_coord()
    try:
        C_coord = residue['C'].get_coord()
    except:
        C_coord = temp_atom.get_coord()
    try:
        O_coord = residue['O'].get_coord()
    except:
        O_coord = temp_atom.get_coord()

    coord = np.vstack([N_coord, CA_coord, C_coord, O_coord])
    AA_coord.append(coord)

m ../SAbDab_20221124/all_structures/raw/7pgb.pdb


In [20]:
residue.get_resname(), residue.get_id(), len(AA_coord), AA_coord[0], AA_coord[-1]

('LHG',
 ('H_LHG', 302, ' '),
 219,
 array([[-95.963,   7.249, -59.086],
        [-95.747,   7.294, -60.528],
        [-95.821,   8.724, -61.056],
        [-95.13 ,   9.078, -62.011]], dtype=float32),
 array([[-62.04 ,  -6.915, -42.951],
        [-60.975,  -6.76 , -41.949],
        [-59.57 ,  -6.98 , -42.506],
        [-58.577,  -6.612, -41.876]], dtype=float32))

In [21]:
with open("./data/data.json", "wb") as f:
    pickle.dump(seqs, f)
f.close()

# 滤掉Aseq、Hseq、Lseq为空的

In [22]:
data = pickle.load(open("./data/data.json", "rb"))
len(data)

5403

In [23]:
data1 = []

for i in tqdm(range(len(data))):
    if data[i]["Aseq"][0]=="" or data[i]["Aseq"][0]=="**":
        print("delete ", i)
    else:
        data1.append(data[i])
len(data1)

100%|██████████████████████████████████████████████████████████████████████████| 5403/5403 [00:00<00:00, 772676.34it/s]

delete  118
delete  377
delete  410
delete  413
delete  611
delete  695
delete  1186
delete  1307
delete  1333
delete  2039
delete  2669
delete  2695
delete  2782
delete  3131
delete  3223
delete  3304
delete  3514
delete  3569
delete  3579
delete  4188
delete  4235
delete  4247
delete  4265
delete  4363
delete  4544
delete  4790
delete  4924
delete  5048
delete  5190


5374

In [24]:
with open("./data/data.json", "wb") as f:
    pickle.dump(data1, f)
f.close()